---
- name: Download Zabbix Repository Ubuntu
  get_url: 
    url: https://repo.zabbix.com/zabbix/6.1/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.1-1%2Bubuntu20.04_all.deb
    dest: /tmp/zabbix-release_6.1-1+ubuntu20.04_all.deb
  
- name: Install repo zabbix
  apt:
    deb: /tmp/zabbix-release_6.1-1+ubuntu20.04_all.deb
    state: present

- name: Update SO Ubuntu
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Install Zabbix Agent Ubuntu
  apt:
    name: zabbix-agent
    state: latest
  
- name: Copy template zabbix-agent.conf Ubuntu
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf

- name: Start service
  service: name=zabbix-agent state=restarted  enabled=yes
...